### PR TITLE
feat(community-skeleton-provider): add rounded corners to image skeleton

### PR DESCRIPTION
**Pull request by viktorbilyk**
## Related issues

See #425 

## Description

This PR adds ability to create image skeleton with rounded corners.

## Checklist before submitting pull request

- Commits follow our [Developer Guide](https://github.com/telus/tds-community/blob/chore/template-hints/.github/CONTRIBUTING.md)
- [x] New code is unit tested
- [x] make sure visual and accessibility tests pass
- [x] make sure code builds

### CODE REVIEW

**Review by affansajid — DISMISSED** [review]
The PR looks good, we can update the commit change so that it's not a breaking change. This should be good for a feature bump `@tds/community-skeleton-provider: 2.0.6 => 2.1.0`

**Comment by viktorbilyk** [comment]
> The PR looks good, we can update the commit change so that it's not a breaking change. This should be good for a feature bump `@tds/community-skeleton-provider: 2.0.6 => 2.1.0`

@affansajid I can update PR, so we don't use shared styles library and border-radius is fixed at 4px that way it's not a breaking change. Otherwise, shared styles needs to be included, so I believe it should be marked as breaking change. Other option is I can just amend commit message without any other changes. Please let me know, what option you think is preferable

**Comment by jraff** [comment]
@viktorbilyk adding `@tds/shared-styles` by itself is not a breaking change.

Please see https://tds.telus.com/contributing/developer-guide.html#commit-format for guidelines around breaking changes, minor patches, and fixes.

**Comment by viktorbilyk** [comment]
@jraff Ok, I have amended the commit, so it is not a breaking change anymore

**Review by jraff — APPROVED** [review]

**Pull request merged**
